q1: MaxHeap.o MinHeap.o MedianHeap.o main.o
	g++ MaxHeap.o MinHeap.o MedianHeap.o main.o -o q1

MaxHeap.o: MaxHeap.cpp
	g++ -c MaxHeap.cpp

MinHeap.o: MinHeap.cpp
	g++ -c MinHeap.cpp

MedianHeap.o: MedianHeap.cpp
	g++ -c MedianHeap.cpp

main.o: main.cpp
	g++ -c main.cpp
	
